practica2/api/urls.py
from django.urls import path, include

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('categoria', views.CategoriaView.as_view()),
    path('post', views.PostView.as_view()),
    path('categoria/<int:pk>/', views.CategoriaDetailView.as_view()),
    path('post/<int:pk>/', views.PostDetailView.as_view()),
]

practica2/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    #path('post', views.post, name='post')
    path('post/<int:post_id>/', views.post, name='post'),
    path('post/', views.post, name='post'),
]

practica2/practica2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

practica2/api/models.py
from django.db import models

# Create your models here.

practica2/blog/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nombre
    
class Post(models.Model):
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200)

    def __str__(self):
        return self.titulo

practica2/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics

from blog.models import Categoria, Post
from .serializers import CategoriaSerializer, PostSerializer

class IndexView(APIView):
    def get(self, request):
        lista_categorias = Categoria.objects.all()
        serializer_categoria = CategoriaSerializer(lista_categorias, many=True)
        return Response(serializer_categoria.data)

class CategoriaView(generics.ListCreateAPIView):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer

class CategoriaDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Categoria.objects.all()
    serializer_class = CategoriaSerializer

class PostView(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

class PostDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

practica2/blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render

# Create your views here.
def index(request):
    return render(request,'index.html')

def post(request):
   return render(request,'post.html')


#  def post(request, post_id):
#      post = get_object_or_404(Post, pk = post_id)
#      return render(request, 'post.html', {'post': post})

practica2/blog/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <!-- Blog entries-->
    <div class="col-lg-8">
        <!-- Nested row for non-featured blog posts-->
        <div class="row">
                <!-- Blog post-->
                <div class="card mb-4">
                    <div class="card-body">
                        
                        <h2 class="card-title h4">Titulo 1</h2>
                        <p class="card-text">Post</p>
                    </div>
                </div>
                <!-- Blog post-->
                <div class="card mb-4">
                    <div class="card-body">
                        
                        <h2 class="card-title h4">Titulo 2</h2>
                        <p class="card-text">Post2s</p>
                    </div>
                </div>
        </div>
    </div>
    <!-- Side widgets-->
    <div class="col-lg-4">
        <div class="card mb-4">
            <div class="card-header">Categorias</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-0">
                            <li><a href="{% url 'blog:post' %}">Camisetas</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

practica2/blog/templates/layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- CABECERA -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">BLOG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Bienvenido a mi blog</h1>
                </div>
            </div>
        </header>
        <!-- CABECERA -->
        <!-- CONTENIDO -->
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <!-- CONTENIDO -->
        <!-- PIE DE PAGINA -->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
        <!-- PIE DE PAGINA -->
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

practica2/blog/templates/post.html
{% extends 'index.html' %}{% block content %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        <h1>Post</h1>
        <h1>{{ post.titulo }}</h1>
    </div>
</div>
{% endblock %}